name: ❓️ Question Request
description: Request an answer
title: "[Question]: "
labels: ["Type: Question", "Status: Triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Question
      description: A clear and concise description of your question.
      placeholder: Tell us what you want to know!
    validations:
      required: true
  - type: checkboxes
    id: search
    attributes:
      label: Search
      options:
        - label: I have used the search function to check whether someone else has already asked the same question.
          required: true
